# Generated by Django 6.0.1 on 2026-02-02 15:58

import uuid
from django.db import migrations, models


def generate_unique_share_ids(apps, schema_editor):
    """Generate unique UUIDs for existing invoices."""
    Invoice = apps.get_model('billing', 'Invoice')
    for invoice in Invoice.objects.all():
        invoice.share_id = uuid.uuid4()
        invoice.save(update_fields=['share_id'])


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        # First add the field without unique constraint
        migrations.AddField(
            model_name="invoice",
            name="share_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
        # Generate unique UUIDs for existing records
        migrations.RunPython(generate_unique_share_ids, migrations.RunPython.noop),
        # Now make it unique and non-null
        migrations.AlterField(
            model_name="invoice",
            name="share_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
