# Generated by Django 6.0.1 on 2026-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_add_share_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="labour_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="material_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
