# Generated by Django 6.0.1 on 2026-02-11 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactenquiry",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enquiries",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="contactenquiry",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contactenquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("converted", "Converted"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
    ]
