# Generated by Django 6.0.1 on 2026-03-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="contact_person",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name="customer",
            name="pincode",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
