# Generated by Django 6.0.1 on 2026-03-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotations", "0002_add_share_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="quotation",
            name="labour_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional labour costs (e.g., for repairs)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="quotation",
            name="material_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Additional material costs (e.g., for repairs)",
                max_digits=12,
            ),
        ),
    ]
